export interface PresentationProps {
  alignmentBaseline?: any,
  baselineShift?: any,
  clip?: any,
  clipPath?: any,
  clipRule?: any,
  color?: any,
  colorInterpolation?: any,
  colorInterpolationFilters?: any,
  colorProfile?: any,
  colorRendering?: any,
  cursor?: any,
  direction?: any,
  display?: any,
  dominantBaseline?: any,
  enableBackground?: any,
  fill?: any,
  fillOpacity?: any,
  fillRule?: any,
  filter?: any,
  floodColor?: any,
  floodOpacity?: any,
  fontFamily?: any,
  fontSize?: any,
  fontSizeAdjust?: any,
  fontStretch?: any,
  fontStyle?: any,
  fontVariant?: any,
  fontWeight?: any,
  glyphOrientationHorizontal?: any,
  glyphOrientationVertical?: any,
  imageRendering?: any,
  kerning?: any,
  letterSpacing?: any,
  lightingColor?: any,
  markerEnd?: any,
  markerMid?: any,
  markerStart?: any,
  mask?: any,
  opacity?: any,
  overflow?: any,
  pointerEvents?: any,
  shapeRendering?: any,
  solidColor?: any,
  solidOpacity?: any,
  stopColor?: any,
  stopOpacity?: any,
  stroke?: any,
  strokeDasharray?: any,
  strokeDashoffset?: any,
  strokeLinecap?: any,
  strokeLinejoin?: any,
  strokeMiterlimit?: any,
  strokeOpacity?: any,
  strokeWidth?: any,
  textAnchor?: any,
  textDecoration?: any,
  textRendering?: any,
  transform?: any,
  unicodeBidi?: any,
  vectorEffect?: any,
  visibility?: any,
  wordSpacing?: any,
  writingMode?: any,
}

export interface CoreProps {
  className?: any,
  style?: any,
  id?: any,
  tabIndex?: any,
}

export interface PathProps {
  d?: any,
  pathLength?: any,
}

export interface SvgProps {
  height?: any,
  width?: any,
  x?: any,
  y?: any,
  preserveAspectRatio?: any,
  viewBox?: any,
}

export interface EventProps {
  onActivate?: any,
  onCancel?: any,
  onCanPlay?: any,
  onCanPlaythrough?: any,
  onChange?: any,
  onClick?: any,
  onClose?: any,
  onCueChange?: any,
  onDblClick?: any,
  onDrag?: any,
  onDragEnd?: any,
  onDragEnter?: any,
  onDragExit?: any,
  onDragLeave?: any,
  onDragOver?: any,
  onDragStart?: any,
  onDrop?: any,
  onDurationChange?: any,
  onEmptied?: any,
  onEnded?: any,
  onError?: any,
  onFocus?: any,
  onFocusIn?: any,
  onFocusOut?: any,
  onInput?: any,
  onInvalid?: any,
  onKeyDown?: any,
  onKeyPress?: any,
  onKeyUp?: any,
  onLoad?: any,
  onLoadedData?: any,
  onLoadedMetadata?: any,
  onLoadStart?: any,
  onMouseDown?: any,
  onMouseEnter?: any,
  onMouseLeave?: any,
  onMouseMove?: any,
  onMouseOut?: any,
  onMouseOver?: any,
  onMouseUp?: any,
  onMouseWheel?: any,
  onPause?: any,
  onPlay?: any,
  onPlaying?: any,
  onProgress?: any,
  onRateChange?: any,
  onReset?: any,
  onResize?: any,
  onScroll?: any,
  onSeeked?: any,
  onSeeking?: any,
  onSelect?: any,
  onShow?: any,
  onStalled?: any,
  onSubmit?: any,
  onSuspend?: any,
  onTimeUpdate?: any,
  onToggle?: any,
  onVolumeChange?: any,
  onWaiting?: any,
}


export default CoreProps;
